name: AWS ML Pipeline
on:
  push:
    branches:
      - main

jobs:
  deploy:
    needs: train
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Check Out Repository
        uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: results
          path: outputs
      - name: Deploy Model
        run: python src/deploy.py --model outputs/model.pth
      - id: measurement-4
        name: Record Measurement After Deploy Model
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Deploy Model
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - id: measurement-4
        name: Record Measurement After Install Dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install Dependencies
          task: get-measurement
      - name: Load Dataset
        run: python src/load_data.py
      - id: measurement-6
        name: Record Measurement After Load Dataset
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Load Dataset
          task: get-measurement
      - name: Train Model
        run: python src/train.py --epochs ${{ inputs.Epochs }} --lr ${{ inputs.LR
          }}
      - id: measurement-8
        name: Record Measurement After Train Model
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Train Model
          task: get-measurement
      - name: Evaluate Metrics
        run: python src/evaluate.py --model outputs/model.pth
      - id: measurement-10
        name: Record Measurement After Evaluate Metrics
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Evaluate Metrics
          task: get-measurement
      - name: Save Results
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: outputs
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
